version: '3'
services:
    sneakeria:
        build:
            context: ./sneakeria
            args:
                VUE_APP_API: ${VUE_APP_API}
        ports:
            - 80:80
    api:
        build:
            context: ./sneakeria/api
        ports:
            - 5000:5000
