version: '3'
services:
    app:
        build:
            context: ./app
            args:
                VUE_APP_API: ${VUE_APP_API}
        ports:
            - 80:80
    api:
        build:
            context: ./app/api
        ports:
            - 5000:5000
